target("Lib_CDX12")
    set_kind("static")
    add_files("src/**.cpp")
    add_headerfiles("include/**.h")
    add_includedirs("include", {public = true})
    set_pcxxheader("include/CDX12/pch.h")
    add_packages("vcpkg::directxtk12")
    add_links("d3d12", "dxgi", "dxguid", "d3dcompiler")
target_end()